update

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -15,12 +15,12 @@ jobs:
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
-      - name: Failed step
-#      - name: Successful step
+#      - name: Failed step
+      - name: Successful step
         run: |
-          echo "I will fail"
-          exit 1
-#          echo "I will succeed"
-#          exit 0
+#          echo "I will fail"
+#          exit 1
+          echo "I will succeed"
+          exit 0
       - name: Say goodbye
         run: echo "Goodbye!"
